name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Sitemap Generator
        run: |
          npm install
          node generate-sitemap.js

      - name: Commit sitemap.xml
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add sitemap.xml
          git commit -m "🔄 Auto-update sitemap.xml" || echo "No changes to commit"
          git push
